# docker-compose.yml
version: "3"
services:
  node-app:
    build: ./
    environment:
      DB_HOST: mongodb://mongo-app:27017
    ports:
      - 80:80
      - 3000:3000
    depends_on:
      - mongo-app
    command: bash -c "npm i && node seeds/seed.js && npm run start"

  mongo-app:
    image: mongo
    ports:
      - 27017:27017
